name: ci

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            test_script: .\test.ps1
          - os: ubuntu-latest
            test_script: ./test.sh
          - os: macos-latest
            test_script: ./test.sh

    steps:
        - name: Checkout
          uses: actions/checkout@v2.3.3

        - uses: microsoft/setup-msbuild@v1.0.2
          if: matrix.os == 'windows-latest'

        - name: Build and test
          run: ${{ matrix.test_script }}
