name: release

on:
  push:
    branches:
      - release/*
  pull_request:
jobs:
  build:
    name: NuGet Pack
    runs-on: macos-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v2.3.3

        - run: mkdir nupkg

        - name: Build and test
          run: >- 
            dotnet pack -c release 
            -o .
            /p:CraftRelease=true 
            src/UnoptimizedAssemblyDetector/UnoptimizedAssemblyDetector.csproj

        - name: Archive Artifacts
          uses: actions/upload-artifact@v2
          with:
            name: ${{ github.sha }}
            path: |
              ${{ github.workspace }}/*.nupkg
